FROM maven:3.8.5-openjdk-17-slim AS build

WORKDIR /usr/src/app

COPY pom.xml .
COPY src ./src
COPY .env .

RUN mvn clean install

FROM openjdk:17.0.2-jdk-slim-buster

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
